TRACE_ID_HEADER = 'X-B3-TraceId'
SPAN_ID_HEADER = 'X-B3-SpanId'
PARENT_SPAN_ID_HEADER = 'X-B3-ParentSpanId'
FLAGS_HEADER = 'X-B3-Flags'
SAMPLED_HEADER = 'X-B3-Sampled'

ZIPKIN_CONFIG_SECTION = 'ZIPKIN'
HANDLER_KEY = 'HANDLER'
HANDLER_PARAMS_KEY = 'HANDLER_PARAMS'
